export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAIL = "UPLOAD_FAIL";
export const IMPORT_SUCCESS = "IMPORT_SUCCESS";
export const IMPORT_FAIL = "IMPORT_FAIL";
export const GETMASTER_SUCCESS = "GETMASTER_SUCCESS";
export const GETMASTER_FAIL = "GETMASTER_FAIL";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";