export const GETEXPORT_SUCCESS = "GETEXPORT_SUCCESS";
export const GETEXPORT_FAIL = "GETEXPORT_FAIL";
export const EXPORT_SUCCESS = "EXPORT_SUCCESS";
export const EXPORT_FAIL = "EXPORT_FAIL";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";